### ISSUE TITLE
Focused widget crashes whole bar when no icon present in desktop file

### ISSUE THREAD

**Issue by ferrreo** [JakeStanger/ironbar#137]
**Describe the bug**
I accidentally forgot to add an icon to my kitty.desktop file and when using the focused widget in ironbar and opening an instance of kitty the whole bar crashes 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install kitty
2. Setup ironbar with focused widget enabled in config
3. Remove the icon line from kitty.desktop file if present
4. Open and focus an instance of kitty
5. Ironbar crashes

**Expected behaviour**
It should just not show an icon if there isn't one and just use the window title and not crash

**System information:**
 - Distro: Ubuntu 22.10/PikaOS
- Compositor: Hyprland
 - Ironbar version: 0.11.0

**Configuration**
Nothing special just add focused widget with icons turned on

**Additional context**
Nothing in the logs or tty when it crashes it just disappears

**Screenshots**
N/A

**Comment by JakeStanger** [comment]
Hey, would you mind sharing the .desktop file please so that I have an exact replica? Could you also let me know what icon theme you are using, and try running ironbar without explicitly setting one?

This seems odd behaviour since plenty of icon themes have a dedicated Kitty icon (both Adwaita and Paper at least), so it will use that before ever hitting the desktop file. If it does get as far as reading the desktop file, Ironbar should just silently continue or log an error if an icon entry can't be found. I wonder if it's coming from GTK, hence the hard crash.

**Comment by howardcoldham** [comment]
`[Desktop Entry]
Version=1.0
Type=Application
Name=kitty
GenericName=Terminal emulator
Comment=Fast, feature-rich, GPU based terminal
TryExec=kitty
Exec=kitty
Icon=kitty
Categories=System;TerminalEmulator;`

This is a default kitty desktop file that causes the issue. To fix I put a full path to the icon provided alongside kitty.

**Comment by ferrreo** [comment]
[Desktop Entry]
Version=1.0
Type=Application
Name=kitty
GenericName=Terminal emulator
Comment=Fast, feature-rich, GPU based terminal
TryExec=kitty
Exec=kitty
Icon=kitty
Categories=System;TerminalEmulator;

This is a default kitty desktop file that causes the issue. To fix I put a full path to the icon provided alongside kitty.

**Comment by JakeStanger** [comment]
That file works fine for me.

> Could you also let me know what icon theme you are using, and try running ironbar without explicitly setting one?

**Comment by ferrreo** [comment]
I can't replicate it now even on older builds, so I guess we should put it down to gtk doing something super weird at the time.
