### ISSUE TITLE
embedded rofi-like menu

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [JakeStanger/ironbar#194]
whats your thoughts on a widget that implements similar behavior to dmenu/rofi? im willing to implement this myself just wanna check before i start any kind of work on it.

**Comment by JakeStanger** [comment]
Hey, thanks for checking with me prior.

I'd say something like that is out of scope of Ironbar, because otherwise we start seeing the scope extend past being a bar and into the territory of being a whole UI kit or shell.

If you want to work on it as a separate project though, I'd be happy to co-operate to see how we can integrate the two.

---

FYI, there's a GTK rofi-like menu called [anyrun](https://github.com/Kirottu/anyrun/tree/master/) also written in Rust you might want to have a look at.

**Comment by SomeGuyNamedMy** [comment]
ill go ahead and close this issue then, thanks for taking the time to respond!!
