### ISSUE TITLE
[Launcher] Incorrect programs being opened

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#222]
**Describe the bug**
Launcher does not open the correct programs. For example, `thunar` opens the bulk renamer.

**To Reproduce**

1. Add `thunar` to launcher
2. Open `thunar`

**Expected behavior**
File browser is opened.

**System information:**
 - Distro: NixOS
- Compositor: Hyprland
 - Ironbar version: https://github.com/JakeStanger/ironbar/commit/f8d8c063008340922b20aa665d8f893ab63e82d7

**Additional context**

- https://github.com/nwg-piotr/nwg-dock-hyprland/issues/5

**Comment by JakeStanger** [comment]
Hey are you able to confirm how both programs were installed, and if possible the absolute path to their desktop files please?

The opening process works by finding the desktop file and passing that to gtk-launch. There have been some recent changes to the code that finds the file so that might be a culprit.

**Comment by donovanglover** [comment]
Looks like home manager packages are in `/etc/profiles/per-user/user/share/applications` and system packages are in `/run/current-system/sw/share/applications/`. Both are in `XDG_DATA_DIRS`.

Thunar has different `.desktop` files for the bulk renamer and the usual file browser.

- `/run/current-system/sw/share/applications/thunar.desktop`
- `/run/current-system/sw/share/applications/thunar-bulk-rename.desktop`

**Comment by yavko** [comment]
> Looks like home manager packages are in `/etc/profiles/per-user/user/share/applications` and system packages are in `/run/current-system/sw/share/applications/`. Both are in `XDG_DATA_DIRS`.
> 
> Thunar has different `.desktop` files for the bulk renamer and the usual file browser.
> 
> - `/run/current-system/sw/share/applications/thunar.desktop`
> - `/run/current-system/sw/share/applications/thunar-bulk-rename.desktop`

So I *think* I found it, in this code it's checking if any field "contains" it, so obviously it's going to be positive for `thunar-bulk-renaner`, I mean it includes thunar. But I'm not sure idk much about this code.
https://github.com/JakeStanger/ironbar/blob/master/src/desktop_file.rs#L110-L115

**Comment by JakeStanger** [comment]
Ah yeah I think you're correct. The fix should just be to do a first pass that checks for an exact match, then do the `contains` in a second pass

**Comment by JakeStanger** [comment]
Turns out it was actually incorrectly matching on the file name before reading any of the desktop files.

I've tested the above with `thunar` and `thunar-bulk-rename` and both now seem to be working reliably. It also shimmies the logic around a bit to try and prevent the same thing happening in other places. 

If you're able to, could you give it ago yourself and let me know if it does the trick or you encounter any other false matches please?
