### ISSUE TITLE
Missing workspace documentation for corn

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#29]
https://github.com/JakeStanger/ironbar/wiki/workspaces
Corn seems very weird.

**Comment by JustSimplyKyle** [comment]
Thanks!

**Comment by JakeStanger** [comment]
Hey nice spot, thanks. That's resolved now. 

> Corn seems very weird.

The language is still quite experimental, so if you do have any feedback I'm all ears. Feel free to open an issue or discussion over at [the repo](https://github.com/jakestanger/corn)

Part of the reason the bar supports the 4 config formats though is because everybody's got different preferences around that, so don't feel compelled to use it.
