### ISSUE TITLE
Bar is always on top

### ISSUE THREAD

**Issue by Relwi** [JakeStanger/ironbar#49]
When I open some game or app in fullscreen, the bar still appears.

**Comment by JakeStanger** [comment]
This isn't an issue I've ever faced. Could you please share some details so I can investigate? Config, distro, compositor, etc...

**Comment by Relwi** [comment]
Config: Is a normal config, I set the position, height and the modules, I don't have a style.css (I'm going to upload the config.toml when I reach home)

Distro: Arch Linux

Compositor: Labwc 0.5.3 (wlroots 0.16.1 just reach the stable repo, when they update the AUR of Labwc using the stable wlroots, I'm going to try again)

**Comment by JakeStanger** [comment]
Okay, please try again with the latest Labwc and let me know. 

Since ironbar uses gtk-layer-shell, it basically requests a surface from the compositor, so that should be handling the fullscreen logic. That leads me to believe labwc is the likely culprit here, but I'll have to do some more testing to be sure. If you're able to see if the problem still occurs for you in sway/hyprland that'd be great.

**Comment by Relwi** [comment]
Yep, the issue was solved in the new version of Labwc, you was right. Thanks!
