### ISSUE TITLE
Volume module

### ISSUE THREAD

**Issue by pinkcreeper100** [JakeStanger/ironbar#50]
A volume module with a popup widget that has a slider. option to choose backend (wpctl, pactl, etc). usage of on-scroll events to change volume without opening the widget.

**Comment by JakeStanger** [comment]
Happy to add this. I'd like to see if I can get a proper mixer too (like the Win7 one) allowing you to change input/output/program volumes individually where supported (ie Pulse or Pipewire).

**Comment by pinkcreeper100** [comment]
That would be nice

**Comment by p00f** [comment]
> Happy to add this. I'd like to see if I can get a proper mixer too (like the Win7 one) allowing you to change input/output/program volumes individually where supported (ie Pulse or Pipewire).

What if you just open pavucontrol on click

**Comment by JakeStanger** [comment]
That could be achieved currently with the `custom` module without much work.

My intention for any "proper" modules is that they offer a more integrated experience, and don't rely on external software where possible. Also, I've started work on the client code for this already :)

**Comment by Phant80m** [comment]
how do i get the buttom to display the audio.

**Comment by JakeStanger** [comment]
Nothing has been implemented yet

**Comment by yavko** [comment]
I think a good starting point would be replicating what kde does, though I think kde's design isn't perfect so maybe could be built on

**Comment by Phant80m** [comment]
hmmmm

**Comment by Pyvonix** [comment]
A bar that already implement a good volume's widget is [the waybar with its PulseAudio plugin](https://github.com/Alexays/Waybar/wiki/Module:-PulseAudio) that offer an easy to:
- format the current volume,
- select an icon depending the used sound output/input,
- let the user choose its sound mixer.

That could be a good reflection way.
And will be amazing to see something similar in Ironbar!

**Comment by yavko** [comment]
> A bar that already implement a good volume's widget is [the waybar with its PulseAudio plugin](https://github.com/Alexays/Waybar/wiki/Module:-PulseAudio) that offer an easy to:
> - format the current volume,
> - select an icon depending the used sound output/input,
> - let the user choose its sound mixer.
> 
> That could be a good reflection way.
> And will be amazing to see something similar in Ironbar!

Waybar's doesn't have a GUI tho. Plus you could already do the same as waybar does with ironbar's built in features.

**Comment by Pyvonix** [comment]
> Waybar's doesn't have a GUI tho. 

Both bars are made on the top of GTK. It's true that Waybar doesn't have real "GUI" _(if you mean possibility to pop a box or container)_, but with some Wayland's trick _(catching the window' name)_ you could make the mixer appear as floating windows the desired position. Realized with `pavucontrol` on Sway the result is transparent.

> Plus you could already do the same as waybar does with ironbar's built in features.

Not completely agree.
After a very painful configuration, I was able to achieve something "_like_" a mixer using: `button`, `label` and `progress` based on the doc's example. But why doesn't offering `{volume}` keyword like the `sys_info` module did?

And I will point out for the moment I haven't found a way dynamically changes an icon depending the audio output (e.g. headphones, speakers, etc... ) or the audio level (e.g. mute, low, high, ...). 
I didn't look into using an external script because I really don't like doing it that way.

I'd really like ironbar and there are little things that could make it even better.

**Comment by JakeStanger** [comment]
> But why doesn't offering {volume} keyword like the sys_info module did?

This is achievable using an ironvar and/or script currently. 

I understand not wanting to rely heavily on scripts, as it does add some performance and maintenance overhead. That's why I want a native module :)

The thing is with the volume module is almost all the work is getting a working client. Once that's done, the rest of the implementation *should* be relatively straightforward; I may not release a full mixer interface immediately but I'd want the ability to show and change master volume for the current output device at a minimum. Unfortunately I've not had much time recently to look at this, and any previous attempts have mostly involved banging my head against walls so it might be a while still.

The thing is with the volume module,

**Comment by JakeStanger** [comment]
I've just opened a draft PR (linked above) with the initial version of the module. It's not quite complete, but stable enough to start playing around with. Full details in the PR.
