### ISSUE TITLE
Nautilus won't open from a launcher

### ISSUE THREAD

**Issue by madfanat** [JakeStanger/ironbar#580]
I even tried to reinstall the distro, but it still doesn't work. If the issue is not related to ironbar, then the only thing it could be related to is polkit (I don't use systemd and use seatd instead of elogind). Could you please check and let me know if it works for you.

https://github.com/JakeStanger/ironbar/assets/168630462/39bfd4cd-74d4-4903-9541-7a1ace61d6cc

P.S. I can run nautilus from terminal and it works

**Comment by yavko** [comment]
Logs would be cool to see, but anyway, I would try running nautilus in your terminal with `gtk-launch` (it takes a desktop file path), since that's what ironbar uses to launch things in the launcher. Also, I would suggest the next time you make an issue, to use the bug report template so you would've known to provide logs, and config.

**Comment by JakeStanger** [comment]
> Logs would be cool to see

Debug logs *and* config please - help me help you.

**Comment by madfanat** [comment]
> `gtk-launch`
Ohhhh I'm sorry, that's my bad. I didn't know that ironbar uses this and corresponding appliction address structure. Fixed the issue by changing "nautilus" to "org.gnome.Nautilus".

**Comment by JakeStanger** [comment]
FYI there are plans to improve this in #487
